#!/usr/bin/env python3

import asyncio
import sys
import websockets
import os

if len(sys.argv) < 3:
    print(f"Usage: {os.path.basename(__file__)} <ws-url> <command>")
    sys.exit(1)

ws_url = sys.argv[1]
command = ["sh", "-c"]
command.extend(sys.argv[2:])


async def send_live_output():
    process = await asyncio.create_subprocess_exec(
        *command, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT
    )

    async with websockets.connect(ws_url) as ws:
        assert process.stdout is not None
        async for line in process.stdout:
            await ws.send(line.decode().rstrip())

    await process.wait()


if __name__ == "__main__":
    asyncio.run(send_live_output())
